# Generated by Django 4.0.6 on 2022-08-04 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('monthly_price', models.IntegerField()),
                ('yearly_price', models.IntegerField()),
                ('video_quality', models.CharField(max_length=100)),
                ('resolution', models.CharField(max_length=150)),
                ('devices', models.CharField(max_length=100)),
                ('active_screens', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=150)),
                ('plan_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assignment.plan')),
            ],
        ),
    ]
