# Generated by Django 4.0.6 on 2022-08-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_alter_user_plan_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plan_period',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
