# Generated by Django 4.0.6 on 2022-08-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0004_user_plan_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_loggedin',
            field=models.BooleanField(default=False),
        ),
    ]
