# Generated by Django 4.0.6 on 2022-08-05 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0005_user_is_loggedin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='plan_type',
        ),
        migrations.AddField(
            model_name='plan',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assignment.user'),
        ),
    ]
